"STOCK X _ CALC X (e)_ sheet"
C <- c(1,4,6,7,10) -> "x stock"
A <- c(1,2,3,4,5) -> "n values"
B <- C[A] -> "n values"
D <- log(C) -> "log values for x"
E <- cumsum(D) -> "rolling sum of logs"
f <- E/A -> "F"
G <- (D-f) -> "G"
H <- (G*G) -> "should be (G^2)"
I <- cumsum(H) -> "H"
J <- sqrt(I) -> "J"
K <- (D-J) -> "_ CALC X (e)_ sheet"