library(quantmod)
library(TTR)
library(zoo)
library(quantreg)
library(QuantTools)
library(xts)
library(TRADER)
library(Trading)
library(dplyr)
library(backtest)
library(PortfolioAnalytics)
library(portfolio)
library(depmixS4)
#_
SCALE <- (252)
P_input <- c(1,1,2,1,2)
Q_mod <- c(1)
Q_input <- c(1,1,-2,1,-2)*Q_mod
write(P_input, file = "N.csv",
ncolumns = 1,
append = FALSE, sep = "")
Num <- (cumsum(count.fields("N.csv")))
n <- (cumsum(count.fields("N.csv")))
N <- (last(n))
PL <- c(0,0,0,0,0,0,0,0,0,0)
PL_1 <- c(abs(PL))
PL_2 <- sum(PL_1)
PL_3 <- ((PL_1[n])/(PL_2))
POSIT <- cumsum(Q_input)
write(PL_3, file = "EXP.csv",
ncolumns = 1,
append = FALSE, sep = "")
Q <- (data.frame(Q=Q_input))
P <- (data.frame(P=P_input))
MARK <- (P)
Q_BUY <- ifelse(((Q$Q[n] < 0) == TRUE ), Q$Q[n], 0)
Q_SELL <- ifelse(((Q$Q[n] > 0) == TRUE ), Q$Q[n], 0)
P_BUY_MARK <- ifelse(((Q$Q[n] < 0) == TRUE ), P$P[n], 0)
P_SELL_MARK <- ifelse(((Q$Q[n] > 0) == TRUE ), P$P[n], 0)
P_BUY <- (ifelse(((Q$Q[n] < 0) == TRUE ), P$P[n], 0))
P_SELL <- (ifelse(((Q$Q[n] > 0) == TRUE ), P$P[n], 0))
AVG_C_BUY <- weighted.mean(P_BUY, Q_BUY[n])
AVG_C_SELL <- weighted.mean(P_SELL, Q_SELL[n])
#_
A1 <- (AVG_C_BUY*Q_BUY)-((MARK*Q_SELL))
#A2 <- (MARK$P*Q_SELL)+(MARK$P*Q_BUY)
#A3 <- (AVG_C_SELL*Q_SELL)-(MARK$P*Q$Q)
#A4 <- (AVG_C_BUY*Q_BUY)-((AVG_C_SELL*Q_BUY))
#A5 <- (AVG_C_SELL*Q_SELL)-((AVG_C_BUY*Q_BUY))
#A6 <- (AVG_C_BUY*Q_BUY)-((AVG_C_SELL*Q_SELL))
#A7 <- (AVG_C_BUY*Q_SELL)-((AVG_C_SELL*Q_SELL))
#A8 <- (AVG_C_BUY*Q$Q)-((AVG_C_SELL*Q$Q))
#A9 <- (AVG_C_BUY*Q_BUY)-(P_SELL_MARK*Q$Q)
#A10 <- (AVG_C_SELL*Q_SELL)-(MARK$P*Q_BUY)
#A11 <- (AVG_C_SELL*Q_SELL)-((AVG_C_BUY*Q_SELL))
#A12 <- (AVG_C_BUY*Q_BUY)-(MARK$P*Q_SELL)
#A13 <- (AVG_C_SELL*Q_BUY)-((AVG_C_BUY*Q_BUY))
#A14 <- (AVG_C_BUY*Q_SELL)-(MARK$P*Q_SELL)
#A15 <- (AVG_C_SELL*Q_BUY)-(MARK$P*Q_BUY)
#A16 <- (AVG_C_SELL*Q$Q)-(MARK$P*AVG_C_SELL)/(AVG_C_SELL*Q$Q)
#A17 <- (AVG_C_BUY*Q_BUY)-((MARK*Q_SELL))
#A18 <- (AVG_C_BUY*Q$Q)-(MARK$P*Q$Q)
#A19 <- (AVG_C_SELL*Q$Q)-(MARK$P*Q$Q)
#A20 <- (AVG_C_BUY*Q$Q)-(MARK$P*Q$Q)/(AVG_C_BUY*Q$Q)
#A21 <- (AVG_C_SELL*Q$Q)-(MARK$P*Q$Q)/(AVG_C_SELL*Q$Q)
#A22 <- (AVG_C_SELL*Q$Q)-((AVG_C_BUY*Q$Q))
#_
TRADING <- c(A1$P)
MARKET <- c(P_input)
L <- list()
L$TRADING <- xts( TRADING, as.Date((first(n)):(last(n))) )
L$MARKET <- xts( MARKET, as.Date((first(n)):(last(n))) )
OUTPUT <- do.call("merge", L)
#charts.PerformanceSummary(OUTPUT)
charts.PerformanceSummary(cbind(OUTPUT))
x <- cbind(OUTPUT)
Performance <- function(x) {
cumRetx = Return.cumulative(x)
annRetx = Return.annualized(x, scale=SCALE)
sharpex = SharpeRatio.annualized(x, scale=SCALE)
winpctx = length(x[x > 0])/length(x[x != 0])
annSDx = sd.annualized(x, scale=SCALE)
Perf = c(cumRetx, annRetx, sharpex, winpctx, annSDx)
names(Perf) = c("Cumulative Return", "Annual Return","Annualized Sharpe Ratio",
"Win %", "Annualized Volatility")
#Perf = c(cumRetx, annRetx, sharpex, winpctx, annSDx, maxDDx, maxLx)
# names(Perf) = c("Cumulative Return", "Annual Return","Annualized Sharpe Ratio",
# "Win %", "Annualized Volatility", "Maximum Drawdown", "Max Length Drawdown")
return(Perf)
}
cbind(TRADING=Performance(L$TRADING),MARKET=Performance(L$MARKET))
