




if (TRUE) {
  "PRINT THIS QUOTE"
}
#_____THIS IS A COMMENT LINE
if (FALSE) {
  "SKIP ME DONT PRINT THIS QUOTE"
}
#_____THIS IS A COMMENT LINE


INPUT <- 9001
#_____THIS IS BOOLEAN
if ((INPUT > 9000) == TRUE) {
  INPUT = 10
  ANSWER = "ITS OVER 9000"
} else {
  INPUT = -10
  ANSWER = "ITS NOT"
}

INPUT
ANSWER


#THIS IS A VECTOR
VECTOR <- c(1:10)
#THIS IS A CONCATINATED VECTOR
VECTOR_2 <- c(1,0,3,4,5,0,0,8,9,0)
#THIS IS ANOTHER CONCATINATED VECTOR
VECTOR_3 <- c("CATS",1,"DOGS",2,3,"BIRDS","TITS")


ARE_TITS_TRUE <- ifelse(VECTOR_3 == "TITS", TRUE, FALSE)
#IS THIS A NUMBER
JUST_NUMBERS <- as.numeric(VECTOR_3)
#NOT NUMBERS RUN AS NA IF YOUR DOING NUMBERY THINGS THIS REMOVES THE NA
JUST_NUMBERS[is.na(JUST_NUMBERS)] = 0

SUM <- cumsum(JUST_NUMBERS)
  #_____THIS IS A LOGIC GATE
THIS_THING <- ifelse(VECTOR == VECTOR_2, "SAME", "DIFFERANT")

VECTOR
VECTOR_2
THIS_THING
VECTOR_3
ARE_TITS_TRUE
JUST_NUMBERS
JUST_NUMBERS